USE [master]
GO

/****** Object:  Database [SecDB]    Script Date: 2015-04-17 10:24:33 ******/
CREATE DATABASE [SecDB]
GO

ALTER DATABASE [SecDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SecDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SecDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SecDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SecDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SecDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SecDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SecDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SecDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SecDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SecDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SecDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SecDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SecDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SecDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SecDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SecDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SecDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SecDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SecDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SecDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SecDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SecDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SecDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SecDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SecDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SecDB] SET  MULTI_USER 
GO

ALTER DATABASE [SecDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SecDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SecDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SecDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SecDB] SET  READ_WRITE 
GO

